sudo: false
language: c

# Handle submodules manually, since we don't want a recursive checkouts
git:
    submodules: false

before_install:
- git submodule update --init

addons:
  apt:
    sources:
      - hvr-ghc
      - sourceline: 'ppa:sri-csl/formal-methods'
    packages:
      - ghc-8.6.5
      - cabal-install-2.4
      - yices2

script:
  - make tests
